### ISSUE TITLE
Execution of user created applications

### ISSUE THREAD

**Issue by kajolH** [LairdCP/RM1xx-Applications#1]
I want to establish communication between two RM186 LoRa modules. I need the detailed procedure to execute .sb file written in notepad++.

**Comment by thedjnK** [comment]
Hi,

You can do this using the BLE functionality by having one module with the central firmware and another with the peripheral firmware then creating an application for the central device to connect to the peripheral device.

There is a guide for running applications available from the Laird website: https://assets.lairdtech.com/home/brandworld/files/Loading%20and%20Running%20Applications%20with%20UwTerminalX%20-%20RM1xx%20Series.pdf
