### ISSUE TITLE
1537 error due to off by one array size

### ISSUE THREAD

**Issue by Howlinmoon** [LairdCP/RM1xx-Applications#5]
This line:

dim PrevAds$[6]          //Previous adverts (size of 6 adverts)

eventually results in error 1537: RUN_INDEX_TOO_LARGE

One quick fix, is to bump this up to 7.
dim PrevAds$[7]          //Previous adverts (size of 6 adverts)

Or you could modify the advert handler to not exceed index 5 - but I prefer this solution.

**Comment by thedjnK** [comment]
Hi,
Fix has been applied in 3ea11df05f300931fc7fdc40f63ccad715f8b93f
